name: study_scheduler
description: A study scheduler application with AI assistance

# Prevent accidental publishing to pub.dev
publish_to: 'none' 

# App version information
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  
  # State management
  provider: ^6.0.5
  flutter_bloc: ^8.1.3
  bloc: ^8.1.2
  
  # Database
  sqflite: ^2.3.0
  path: ^1.8.3
  
  # Networking
  dio: ^5.3.2
  connectivity_plus: ^4.0.2
  
  # UI components
  flutter_slidable: ^3.0.0
  table_calendar: ^3.0.9
  cached_network_image: ^3.2.3
  
  # Utilities
  intl: ^0.18.1
  shared_preferences: ^2.2.1
  flutter_dotenv: ^5.1.0
  timezone: ^0.9.2
  logger: ^1.4.0
  
  # File handling
  path_provider: ^2.1.1
  file_picker: ^10.1.2
  open_file: ^3.3.2
  url_launcher: ^6.2.5
  
  # Notifications
  flutter_local_notifications: 19.1.0
  http: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mockito: ^5.4.2
  build_runner: ^2.3.3

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
    - .env
    
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
dependency_overrides:
  file_picker:
    git:
      url: https://github.com/miguelpruivo/flutter_file_picker.git
      ref: master          